GET http://localhost:3000/health

@game_id = 1

###
GET http://localhost:3000/api/v1/games
Content-Type: application/json


###
POST http://localhost:3000/api/v1/games
Content-Type: application/json


###
GET http://localhost:3000/api/v1/games/{{game_id}}
Content-Type: application/json


###
POST http://localhost:3000/api/v1/games/{{game_id}}/economy
Content-Type: application/json


###
GET http://localhost:3000/api/v1/games/{{game_id}}/economy/inventory/registry/4
Content-Type: application/json


###
POST http://localhost:3000/api/v1/games/{{game_id}}/economy/inventory/registry
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWURRmnmgcZ6sC6Sm
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="pinataMetadata"

{"name":"item"}
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="20230603155922_init.up.sql"
Content-Type: application/octet-stream

< ./internal/db/migrations/20230603155922_init.up.sql
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="20230727145647_add_users_and_api_keys_and_games_table.down.sql"
Content-Type: application/octet-stream

< ./internal/db/migrations/20230727145647_add_users_and_api_keys_and_games_table.down.sql
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="png-1mb.png"
Content-Type: application/octet-stream

< ./png-1mb.png
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm--
