@game_id = 1
@economy_id = 1

###
# Health Check
GET http://localhost:3000/health


###
# List Game
GET http://localhost:3000/api/v1/games
Content-Type: application/json


###
# Create Game
POST http://localhost:3000/api/v1/games
Content-Type: application/json


###
# Get Game
GET http://localhost:3000/api/v1/games/{{game_id}}
Content-Type: application/json


###
# List Game Economy
GET http://localhost:3000/api/v1/games/{{game_id}}/economies
Content-Type: application/json


###
# Get Game Economy
GET http://localhost:3000/api/v1/games/{{game_id}}/economies/{{economy_id}}
Content-Type: application/json


###
# Create Game Economy
POST http://localhost:3000/api/v1/games/{{game_id}}/economies
Content-Type: application/json


###
# List Game Economy Item
GET http://localhost:3000/api/v1/games/{{game_id}}/economies/{{economy_id}}/items/2
Content-Type: application/json


###
# Create Game Economy Item
POST http://localhost:3000/api/v1/games/{{game_id}}/economies/{{economy_id}}/items
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryWURRmnmgcZ6sC6Sm
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="pinataMetadata"

{"name":"item"}
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="20230603155922_init.up.sql"
Content-Type: application/octet-stream

< ./internal/db/migrations/20230603155922_init.up.sql
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="20230727145647_add_users_and_api_keys_and_games_table.down.sql"
Content-Type: application/octet-stream

< ./internal/db/migrations/20230727145647_add_users_and_api_keys_and_games_table.down.sql
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm
Content-Disposition: form-data; name="file"; filename="png-1mb.png"
Content-Type: application/octet-stream

< ./png-1mb.png
------WebKitFormBoundaryWURRmnmgcZ6sC6Sm--

###
# Enable Behavior Purchase Item
POST http://localhost:3000/api/v1/games/{{game_id}}/economies/{{economy_id}}/behavior/purchase_item/enable
Content-Type: application/json


###
# Disable Behavior Purchase Item
POST http://localhost:3000/api/v1/games/{{game_id}}/economies/{{economy_id}}/behavior/purchase_item/disable
Content-Type: application/json