GET http://localhost:3000/health

@game_id = 3918ba29-75dd-40e9-aa5a-35d83ee75d40

###
GET http://localhost:3000/api/v1/games
Content-Type: application/json


###
GET http://localhost:3000/api/v1/games/{{game_id}}
Content-Type: application/json


###
POST http://localhost:3000/api/v1/games
Content-Type: application/json


###
POST http://localhost:3000/api/v1/games/{{game_id}}/economy
Content-Type: application/json



###
POST http://localhost:3000/api/v1/upload
Content-Type: multipart/form-data; boundary=namespace

--namespace
Content-Disposition: form-data; name="image"; filename="png-1mb.png"
Content-Type: image/png

< ./png-1mb.png
--namespace--
