version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 10

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/database
    command:
      [
        "-path",
        "/database",
        "-database",
        "postgres://postgres:postgres@db:5432/dev?sslmode=disable",
        "up",
      ]
