name: Validate and Lint API spec

on:
  - pull_request

jobs:
  lint:
    name: Validate and Lint OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate and Lint
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: "docs/spec.yml"