name: Test

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          go mod download

      - name: Build check
        run: |
          go build cmd/server/main.go
    
      - name: Run tests
        run: |
          go install github.com/mfridman/tparse/...@latest
          go test -race ./... -v -short -json -timeout=120s --failfast -p=1 | tparse -all -notests -follow